instruments:
        - 'AH2700A'
        - 'LS340'
        - 'LabJack'

name: 'Desert Cryo'

location: 0000

#Defines what channels temperature monitors are connected to
#only need for lakeshore devices
channels_ls:
        contact_stage: 'A'
        cooling_stage: 'B'

#Temperatures to use when recycling
temps:
        T4Ksetpt: 2.8
        T1Ksetpt: 2.8
        Tpump: 39
        T1Kfinal: 0.76
        Tpumpfinal: 6.7
        Tcheck: 0.76             #if the 1K sensor is below this temp the fridge does not recycle
#temperature points for the first the fridge recycles
temps_first:
        T4Ksetpt: 2.8
        T1Ksetpt: 2.8
        Tpump: 39
        T1Kfinal: 0.76
        Tpumpfinal: 6.7

#voltages for the heaters, different voltage settings for recycling and warming up
voltages:
        cooling:
            HS: 6.2
        heating:
            HS: 5.8
            HP: 25

graph:
        - '1K'
        - '4K'
        - '40K'
        - 'pump'
        - 'hs'
        - 'switch'